server:
  port: 8080

spring:
  application:
    name: saga-orchestrator
  datasource:
    url: jdbc:postgresql://localhost:5430/saga_db
    username: saga_user
    password: saga_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

services:
  reservation:
    url: http://localhost:8081/api/reservations
  payment:
    url: http://localhost:8082/api/payments
  notification:
    url: http://localhost:8083/api/notifications
